- name: apt-get install
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - apt-transport-https
      - curl
      - ca-certificates
      - software-properties-common
  become: yes

- name: add apt-key
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: add apt source list
  copy:
    src: files/kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    remote_src: no
  become: yes

- name: apt-mark unhold
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: apt-get install
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - kubelet=1.17.0-00
      - kubeadm=1.17.0-00
      - kubectl=1.17.0-00
      - docker-ce=18.06.1~ce~3-0~ubuntu
  become: yes

- name: apt-mark hold
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: swapoff
  shell: swapoff -a
  become: yes

- name: check if installed kubelet
  stat:
    path: "/var/lib/kubelet/*"
  register: is_installed
  become: yes

- name: kubeadm init
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_eth0.ipv4.address }}
  when: is_installed.stat.exists == False
  ignore_errors: True
  become: yes

- name: make .kube dir
  file:
    path: /home/{{ user }}/.kube
    state: directory

- name: copy kubernetes config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ user }}/.kube/config
    owner: "{{ user }}"
    group: "{{ user }}"
  become: yes

- name: set sysctl for kube network addon flannel
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
  become: yes

- name: apply network addon
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: taint nodes
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-

