apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.5.2

resources:
  - app-of-apps.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: argocd-server
    path: patches/service.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: patches/deployment.yaml
