---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.8.0 (0c0c027)
    fluxcd.io/automated: "true"
  creationTimestamp:
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp:
      labels:
        app: grafana
        io.kompose.service: grafana
    spec:
      containers:
      - image: grafana/grafana:master-ubuntu
        name: grafana
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 200e6
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-claim0
      - image: influxdb:1.7-meta
        name: influxdb
        ports:
        - containerPort: 8086
        resources:
          limits:
            memory: 480e6
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim0
        - mountPath: /etc/influxdb
          readOnly: true
          name: influxdb-conf
      restartPolicy: Always
      volumes:
      - name: grafana-claim0
        persistentVolumeClaim:
          claimName: grafana-claim0
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
      - name: influxdb-conf
        configMap:
          name: influxdb-conf
          items:
          - key: influxdb.conf
            path: influxdb.conf
status: {}
