---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp:
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp:
      labels:
        app: grafana
        io.kompose.service: grafana
    spec:
      containers:
      - image: mackerel/mackerel-container-agent:0.2.0
        name: mackerel
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
        env:
          - name: MACKEREL_CONTAINER_PLATFORM
            value: kubernetes
          - name: MACKEREL_APIKEY
            valueFrom:
              secretKeyRef:
                name: grafana
                key: mackerel_api_key
          - name: MACKEREL_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MACKEREL_KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MACKEREL_KUBERNETES_POD_NAME
            valueFrom:
             fieldRef:
                fieldPath: metadata.name
      - image: grafana/grafana:5.4.3
        name: grafana
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 200e6
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-claim0
      - image: influxdb:1.5
        name: influxdb
        ports:
        - containerPort: 8086
        resources:
          limits:
            memory: 480e6
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-claim0
        - mountPath: /etc/influxdb
          readOnly: true
          name: influxdb-conf
      volumes:
      - name: grafana-claim0
        persistentVolumeClaim:
          claimName: grafana-claim0
      - name: influxdb-claim0
        persistentVolumeClaim:
          claimName: influxdb-claim0
      - name: influxdb-conf
        configMap:
          name: influxdb-conf
          items:
          - key: influxdb.conf
            path: influxdb.conf
status: {}
