kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: influxdb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/influxdb"
