{{- range $key, $value := .Values.applications }}
{{- if $value.enabled | default false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
spec:
  project: conoha
  source:
    repoURL: https://github.com/chroju/sandbox-infrastructure
    path: {{ $value.sourcePath }}
    targetRevision: {{ $value.targetRevision }}
    {{- if $value.helmValueFile | default false }}
    helm:
      valueFiles:
      - {{ $value.helmValueFile }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $value.namespace }}
  {{- if $value.automated }}
  syncPolicy:
    automated:
      prune: {{ $value.prune }}
      selfHeal: {{ $value.selfHeal }}
  {{- end }}
---
{{- end }}
{{- end }}
