apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: conoha
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/chroju/sandbox-infrastructure
  destinations:
  - namespace: external-secrets
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
