apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: conoha
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/chroju/sandbox-infrastructure
  destinations:
  {{- range $namespace := .Values.namespaces }}
  - namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
  {{- end }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
