- hosts: master
  tasks:
  - name: apt-get install
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - curl
        - ca-certificates
        - software-properties-common
  - name: add apt-key
    apt_key:
      url: "{{ item }}"
      state: present
    loop:
      - https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - https://download.docker.com/linux/ubuntu/gpg
  - name: add apt source list
    copy:
      src: files/kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list
      remote_src: no
  - name: apt-get install
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl
        - docker-ce=18.06.1~ce~3-0~ubuntu
  - name: apt-mark hold
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop:
      - kubelet
      - kubeadm
      - kubectl
  - name: swapoff
    shell: swapoff -a
  - name: check if installed kubelet
    stat:
      path: /var/lib/kubelet
    register: is_installed
  - name: kubeadm init
    shell: kubeadm init
    when: is_installed.stat.exists == False
  - name: apply network addon
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
