kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv-volume
  namespace: grafana
  labels:
    type: local
  annotations:
    fluxcd.io/automated: "true"
spec:
  storageClassName: grafana
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"
