kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv-volume
  namespace: grafana
  labels:
    type: local
  annotations:
    fluxcd.io/automated: "true"
spec:
  storageClassName: influxdb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/influxdb"
